export const campaigns=[
  {id:'reference-audit',title:'Trace a claim back to the evidence.',taskId:'atlas-reference-audit-v1',description:'Audit a small public neuro source packet. Separate the claim, the primary evidence, and what remains uncertain.',sourceUrls:['https://www.plneuro.xyz/insights/how-to-obtain-a-complete-human-connectome-at-synaptic-resolution-within-the-next-decade/','https://www.plneuro.xyz/insights/cognitive-dark-matter-measuring-what-ai-misses/'],deliverable:'An evidence ledger: one row per claim, with a primary source and a limitation.'},
  {id:'reproduce-tutorial',title:'Make a result reproducible.',taskId:'neuromatch-reproduction-v1',description:'Choose one public Neuromatch tutorial and reproduce a clearly bounded result. Capture the environment, parameters, and deviations.',sourceUrls:['https://compneuro.neuromatch.io/','https://github.com/NeuromatchAcademy/course-content'],deliverable:'A runnable notebook, an environment manifest, and a comparison to the stated result.'},
] as const
export function buildWorkPacket(campaignId:string,role:string,budgetHintMinutes:number) {
  const c=campaigns.find(c=>c.id===campaignId);if(!c)throw Error('Choose a known pilot recipe')
  if(!['research','reproduce','review'].includes(role))throw Error('Choose a role')
  if(!Number.isFinite(budgetHintMinutes)||budgetHintMinutes<5||budgetHintMinutes>240)throw Error('Local time budget must be 5–240 minutes')
  return {version:1,campaignId:c.id,taskId:c.taskId,title:c.title,status:'proposed-pilot-not-dispatched',role,budgetHintMinutes,budgetIsEnforced:false,sourceUrls:[...c.sourceUrls],instructions:c.description,deliverable:c.deliverable,outputSchema:{taskId:'string',sourceUrl:'https URL',claim:'string',evidenceUrl:'https URL',method:'string',result:'string',limitations:'string',reproductionSteps:'string[]'},verificationRubric:['Resolve each URL and preserve source title/date.','Separate observed evidence from inference.','Record methods, parameters, environment, and unsuccessful attempts.','Human acceptance: an independent person checks the evidence; machine output is not verification.'],stopConditions:['Stop at the local time budget; report incomplete work.','Stop if sources require credentials, personal data, payment, or unpublished materials.','Do not execute untrusted code without your own isolated environment and review.','Do not publish, message people, spend money, or send secrets.'],privacy:'Public source packet only. No keys, tokens, passwords, or private documents. Provider subscriptions and tokens are not interchangeable.'}
}
export type WorkPacket=ReturnType<typeof buildWorkPacket>
export function packetMarkdown(p:WorkPacket) { return `# ${p.title}\n\nProposed pilot — downloaded locally, not dispatched.\n\nTask: ${p.taskId}\nRole: ${p.role}\nLocal time hint: ${p.budgetHintMinutes} minutes (not enforced)\n\n${p.instructions}\n\n## Deliverable\n${p.deliverable}\n\n## Sources\n${p.sourceUrls.map(s=>'- '+s).join('\n')}\n\n## Output schema\n\`\`\`json\n${JSON.stringify(p.outputSchema,null,2)}\n\`\`\`\n\n## Verification rubric\n${p.verificationRubric.map(s=>'- '+s).join('\n')}\n\n## Stop conditions\n${p.stopConditions.map(s=>'- '+s).join('\n')}\n\n${p.privacy}\n` }
export function downloadText(name:string,text:string,type='application/json') { const blob=new Blob([text],{type:`${type};charset=utf-8`});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name.replace(/[^a-zA-Z0-9._-]/g,'-');document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000) }
