"use client";
import { useEffect, useId, useRef, useState, type ReactNode } from 'react';
import { DEMO_CASES, DEMO_NOTIFICATIONS, DEMO_PEOPLE, DEMO_PROPOSALS, DEMO_SUPPORT, DEMO_THREADS, demoCasesFor, demoPointsRemaining, demoThreadHref, type DemoCaseId, type DemoContext, type DemoPerson, type DemoThread } from '@/lib/lab-demo';
import { useDemoCommunity } from '@/components/lab/demo/DemoCommunityProvider';
import { DemoDialog } from '@/components/lab/demo/DemoDialog';
import styles from '@/components/lab/demo/demo.module.css';

export interface DemoFilterProps { caseId?: DemoCaseId; context?: DemoContext; className?: string }
export const DemoChip = () => <span className={styles.chip}>Demo</span>;
export function DemoModeBanner({ className = '', showWhenLive = true }: { className?: string; showWhenLive?: boolean }) {
  const demo = useDemoCommunity(); const [resetting, setResetting] = useState(false);
  if (!demo.available || (!demo.isDemo && !showWhenLive)) return null;
  return <aside className={`${styles.root} ${styles.banner} ${className}`} aria-label="Community preview mode"><div className={styles.bannerCopy}><span className={styles.eyebrow}>{demo.isDemo ? 'DEMO COMMUNITY' : 'YOUR REAL / EMPTY VIEW'}</span><p>{demo.isDemo ? 'Fictional people. Real questions about how science moves.' : 'Demo community hidden. Your genuine local work stays separate.'}</p><small>{demo.isDemo ? 'An illustrative story, not real activity. Replies and signals stay in this browser; nothing is publicly posted.' : 'This switch does not connect a live service or change your profile and drafts.'}</small></div><div className={styles.actions}><button className={styles.button} disabled={!demo.ready} onClick={() => demo.setMode(demo.isDemo ? 'live' : 'demo')}>{demo.isDemo ? 'Show real / empty view' : 'Show demo community'}</button><button className={styles.textButton} disabled={!demo.ready} onClick={() => setResetting(true)}>Reset demo</button></div>{demo.error && <p className={styles.error} role="alert">{demo.error}</p>}{resetting && <DemoDialog title="Reset this demo?" onClose={() => setResetting(false)}><p>Remove your demo replies, follows, saved discussions, point allocations, and notification history in this browser scope. The fictional starting story will remain.</p><p>Your genuine profile, drafts, and view preference will not change. This cannot be undone.</p><div className={styles.actions}><button className={styles.button} onClick={() => setResetting(false)}>Cancel</button><button className={styles.primary} onClick={() => { if (demo.resetDemo(true).ok) setResetting(false); }}>Reset demo changes</button></div>{demo.error && <p role="alert">{demo.error}</p>}</DemoDialog>}</aside>;
}
function PersonButton({ person, onOpen, compact = false }: { person: DemoPerson; onOpen: (p: DemoPerson) => void; compact?: boolean }) {
  return <button className={`${styles.person} ${compact ? styles.compactPerson : ''}`} aria-label={`View ${person.name}’s demo profile`} onClick={() => onOpen(person)}><span className={styles.avatar} aria-hidden="true">{person.initials}</span><span><strong>{person.name}</strong>{!compact && <small>{person.role}</small>}</span></button>;
}
function ProfileDialog({ person, onClose }: { person: DemoPerson; onClose: () => void }) {
  const demo = useDemoCommunity(); const following = demo.state.follows.includes(person.id);
  return <DemoDialog title={person.name} onClose={onClose}><div className={styles.profileIntro}><span className={styles.largeAvatar} aria-hidden="true">{person.initials}</span><div><DemoChip /><p>{person.role}</p><small>Fictional profile · invented role, no organization affiliation</small></div></div><p>{person.bio}</p><h3>Looking for</h3><p>{person.lookingFor}</p><h3>Working through</h3><ul className={styles.linkList}>{DEMO_THREADS.filter(t => person.caseIds.includes(t.caseId)).map(t => <li key={t.id}><a href={demoThreadHref(t.id)}>{t.title} ↗</a></li>)}</ul><button className={styles.button} aria-pressed={following} onClick={() => demo.act({ type: 'follow', personId: person.id })}>{following ? 'Following in demo' : 'Follow in demo'}</button><p className={styles.muted}>A local bookmark, not a follow sent to a person.</p>{demo.error && <p role="alert" className={styles.error}>{demo.error}</p>}</DemoDialog>;
}
export function DemoPeople({ caseId, context, className = '', variant = 'strip' }: DemoFilterProps & { variant?: 'strip' | 'cards' }) {
  const demo = useDemoCommunity(); const [person, setPerson] = useState<DemoPerson | null>(null);
  if (!demo.isDemo) return null;
  const caseIds = demoCasesFor(context, caseId).map(c => c.id);
  const people = DEMO_PEOPLE.filter(p => p.caseIds.some(id => caseIds.includes(id)));
  return <section className={`${styles.root} ${styles.peopleSection} ${className}`} aria-label="Fictional demo people"><div className={styles.row}><h2>People around the question</h2><DemoChip /></div><div className={variant === 'cards' ? styles.peopleCards : styles.peopleStrip}>{people.map(p => <div key={p.id}><PersonButton person={p} onOpen={setPerson} />{variant === 'cards' && <p className={styles.muted}>{p.lookingFor}</p>}</div>)}</div>{person && <ProfileDialog person={person} onClose={() => setPerson(null)} />}</section>;
}
export function DemoNotifications({ className = '' }: { className?: string }) {
  const demo = useDemoCommunity(); const [open, setOpen] = useState(false);
  if (!demo.isDemo) return null;
  const notifications = DEMO_NOTIFICATIONS.filter(n => !demo.state.dismissed.includes(n.id));
  return <div className={`${styles.root} ${styles.notifications} ${className}`}><button className={styles.bell} aria-label={`Demo notifications: ${demo.unreadCount} unread`} aria-haspopup="dialog" aria-expanded={open} onClick={() => setOpen(true)}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" /></svg><span>{demo.unreadCount}</span><DemoChip /></button>{open && <DemoDialog title="Demo notifications" corner onClose={() => setOpen(false)}><p className={styles.muted}>Developments in the illustrative story—not a live inbox.</p>{notifications.length === 0 && <p>No demo notifications left. Reset the demo to restore the story.</p>}<ul className={styles.notificationList}>{notifications.map(n => <li key={n.id}><span className={styles.eyebrow}>{demo.state.read.includes(n.id) ? 'READ' : 'UNREAD'} · DEMO</span><p>{n.label}</p><div className={styles.actions}><a className={styles.textLink} href={n.href} onClick={e => {
      const result = demo.act({ type: 'read', notificationId: n.id });
      if (window.location.pathname === '/lab/demo/') { e.preventDefault(); window.history.replaceState(null, '', n.href); demo.openDiscussion(n.threadId); }
      if (result.ok) setOpen(false);
    }}>{n.action} →</a><button className={styles.textButton} aria-label={`Dismiss: ${n.label}`} onClick={() => demo.act({ type: 'dismiss', notificationId: n.id })}>Dismiss</button></div></li>)}</ul>{demo.error && <p role="alert" className={styles.error}>{demo.error}</p>}</DemoDialog>}</div>;
}
export interface DemoCommunityPanelProps extends DemoFilterProps { title?: string; emptyState?: ReactNode; initialExpandedThreadId?: string; showPeople?: boolean }
export function DemoCommunityPanel({ caseId, context, className = '', title = 'The discussion moves the work', emptyState = null, initialExpandedThreadId, showPeople = false }: DemoCommunityPanelProps) {
  const demo = useDemoCommunity();
  if (!demo.isDemo) return <>{emptyState}</>;
  const caseIds = demoCasesFor(context, caseId).map(c => c.id); const threads = DEMO_THREADS.filter(t => caseIds.includes(t.caseId)); const counts = demo.counts(caseId, context);
  return <section className={`${styles.root} ${styles.panel} ${className}`} aria-label="Demo community discussion"><div className={styles.row}><h2>{title}</h2><DemoChip /></div><p className={styles.muted}>{counts.people} fictional people · {counts.discussions} {counts.discussions === 1 ? 'discussion' : 'discussions'} · {counts.messages} messages. Days label an illustrative sequence, not real time.</p>{threads.length === 0 && <p>No demo discussion matches this context.</p>}{threads.map(t => <Discussion key={t.id} thread={t} initiallyOpen={initialExpandedThreadId === t.id} />)}{showPeople && <DemoPeople caseId={caseId} context={context} />}</section>;
}
export const DemoActivityFeed = DemoCommunityPanel;
function Discussion({ thread, initiallyOpen }: { thread: DemoThread; initiallyOpen: boolean }) {
  const demo = useDemoCommunity(); const id = useId(); const heading = useRef<HTMLHeadingElement>(null); const textarea = useRef<HTMLTextAreaElement>(null);
  const [open, setOpen] = useState(initiallyOpen); const [person, setPerson] = useState<DemoPerson | null>(null); const [replyTo, setReplyTo] = useState<string | undefined>(); const [text, setText] = useState(''); const [message, setMessage] = useState('');
  const proposal = DEMO_PROPOSALS.find(p => p.id === thread.proposalId)!; const caseItem = DEMO_CASES.find(c => c.id === thread.caseId)!;
  const replies = demo.state.replies.filter(r => r.threadId === thread.id);
  useEffect(() => { if (demo.activeThreadId === thread.id) { setOpen(true); heading.current?.focus(); } }, [demo.activeThreadId, demo.navigationRevision, thread.id]);
  const signal = DEMO_SUPPORT.filter(a => a.proposalId === proposal.id).reduce((sum, a) => sum + a.points, 0) + (demo.state.allocations[proposal.id] || 0);
  const chooseReply = (parentId: string) => { setReplyTo(parentId); setMessage(''); textarea.current?.focus(); };
  return <article className={styles.discussion} data-thread={thread.id} id={`demo-discussion-${thread.id}`}><div className={styles.eyebrow}>{caseItem.title}</div><h3 ref={heading} tabIndex={-1}>{thread.title}</h3><p>{caseItem.refinement}</p><div className={styles.discussionMeta}><span>{thread.messages.length + replies.length} messages</span><span>{signal} fictional points</span><span>Outcome still open</span></div><div className={styles.actions}><button className={styles.primary} aria-label={`${open ? 'Close' : 'Open'} discussion: ${thread.title}`} aria-expanded={open} aria-controls={id} onClick={() => setOpen(v => !v)}>{open ? 'Collapse discussion' : 'Read the discussion'} <span aria-hidden="true">{open ? '−' : '↓'}</span></button><button className={styles.button} aria-pressed={demo.state.saves.includes(thread.id)} onClick={() => demo.act({ type: 'save', threadId: thread.id })}>{demo.state.saves.includes(thread.id) ? 'Saved discussion' : 'Save discussion'}</button><a className={styles.textLink} href={demoThreadHref(thread.id)}>Discussion link ↗</a></div>{open && <div id={id} className={styles.expanded}>
    <ol className={styles.messages}>{thread.messages.map(m => {
      const author = DEMO_PEOPLE.find(p => p.id === m.authorId)!; const parent = thread.messages.find(x => x.id === m.parentId); const parentAuthor = DEMO_PEOPLE.find(p => p.id === parent?.authorId);
      return <li key={m.id} className={styles.message}><div className={styles.row}><PersonButton person={author} onOpen={setPerson} compact /><span className={styles.messageKind}>{m.kind}</span></div><small className={styles.muted}>{m.sequence}{parentAuthor ? ` · replying to ${parentAuthor.name}` : ''}</small><p>{m.text}</p><button className={styles.textButton} aria-label={`Reply to ${author.name}: ${m.id}`} onClick={() => chooseReply(m.id)}>Reply to this</button></li>;
    })}{replies.map((r, i) => <li key={r.id} className={`${styles.message} ${styles.localMessage}`}><strong>Your demo note</strong><small>Local addition {i + 1}{r.parentId ? ` · reply to ${DEMO_PEOPLE.find(p => p.id === thread.messages.find(m => m.id === r.parentId)?.authorId)?.name || 'your demo note'}` : ''}</small><p>{r.text}</p><button className={styles.textButton} aria-label={`Reply to your demo note: ${r.id}`} onClick={() => chooseReply(r.id)}>Reply to this</button></li>)}</ol>
    <section className={styles.proposal} aria-label="Revised demo intervention"><span className={styles.eyebrow}>BOUNDED INTERVENTION · REVISION 2</span><h4>{proposal.title}</h4><p>{proposal.hypothesis}</p><dl><dt>Smallest test</dt><dd>{proposal.test}</dd><dt>Contribution to make</dt><dd>{proposal.help}</dd><dt>Keep as evidence</dt><dd>{proposal.artifact}</dd><dt>Outcome / revise</dt><dd>{proposal.outcome}</dd><dt>Design change</dt><dd>{proposal.revision}</dd><dt>Stop condition</dt><dd>{proposal.stop}</dd></dl><div className={styles.row}><span>{signal} fictional points · {demoPointsRemaining(demo.state)} of your demo points left</span><div className={styles.actions}><button className={styles.button} disabled={demoPointsRemaining(demo.state) === 0} onClick={() => demo.act({ type: 'allocate', proposalId: proposal.id, delta: 1 })}>Allocate 1 demo point</button><button className={styles.textButton} disabled={!demo.state.allocations[proposal.id]} onClick={() => demo.act({ type: 'allocate', proposalId: proposal.id, delta: -1 })}>Reclaim 1 point</button></div></div><p className={styles.muted}>A finite interest signal, not money, funding, an impact claim, or an issued Hypercert.</p></section>
    <form className={styles.replyForm} onSubmit={e => { e.preventDefault(); const result = demo.act({ type: 'reply', threadId: thread.id, parentId: replyTo, text }); if (result.ok) { setText(''); setReplyTo(undefined); setMessage('Demo reply saved in this browser. Not publicly posted.'); } else setMessage(result.error || 'Not saved.'); }}><label htmlFor={`${id}-reply`}>Add a useful next step</label><p className={styles.muted}>Challenge the hypothesis, offer a smaller test, or say what evidence is missing.</p>{replyTo && <div className={styles.row}><small>Replying to {DEMO_PEOPLE.find(p => p.id === thread.messages.find(m => m.id === replyTo)?.authorId)?.name || 'your demo note'}</small><button type="button" className={styles.textButton} onClick={() => setReplyTo(undefined)}>Reply to discussion instead</button></div>}<textarea id={`${id}-reply`} ref={textarea} value={text} onChange={e => setText(e.target.value)} rows={4} maxLength={2000} required aria-describedby={`${id}-privacy`} placeholder="A question, a counterexample, a possible test…" /><small id={`${id}-privacy`}>Demo-only reply. Saved locally as “Your demo note,” never as your public identity.</small><button className={styles.primary} type="submit" disabled={!text.trim()}>Save demo reply</button><p className={styles.status} role="status">{message}</p></form>{demo.error && <p role="alert" className={styles.error}>{demo.error}</p>}
  </div>}{person && <ProfileDialog person={person} onClose={() => setPerson(null)} />}</article>;
}
export function DemoCommunityExperience({ showBanner = true, showNotifications = true }: { showBanner?: boolean; showNotifications?: boolean }) {
  const demo = useDemoCommunity(); const [selected, setSelected] = useState<DemoCaseId>('reproducibility'); const [unknown, setUnknown] = useState(false);
  useEffect(() => { const thread = DEMO_THREADS.find(t => t.id === demo.activeThreadId); if (thread) setSelected(thread.caseId); }, [demo.activeThreadId, demo.navigationRevision]);
  useEffect(() => { const query = new URLSearchParams(window.location.search); const target = query.get('discussion'); setUnknown(!!target && !DEMO_THREADS.some(t => t.id === target)); const caseId = query.get('case'); if (DEMO_CASES.some(c => c.id === caseId)) setSelected(caseId as DemoCaseId); }, []);
  const current = DEMO_CASES.find(c => c.id === selected)!;
  return <div className={`${styles.root} ${styles.experience}`}>{showBanner && <DemoModeBanner />}<header className={styles.pageHeader}><div><div className={styles.eyebrow}>OPEN LAB / DEMO COMMUNITY</div><h1>Good questions need<br />more than one mind.</h1><p>Watch a shared bottleneck become a smaller test—and see what changes when the evidence does not cooperate.</p></div>{showNotifications && <DemoNotifications />}</header>{unknown && <p role="status">That demo discussion does not exist. Choose one of the cases below.</p>}{demo.isDemo ? <><div className={styles.workspace}><nav className={styles.caseIndex} aria-label="Demo bottleneck cases"><span className={styles.eyebrow}>THE CASE NOTEBOOK</span>{DEMO_CASES.map((c, i) => <button key={c.id} aria-pressed={c.id === selected} onClick={() => { setSelected(c.id); setUnknown(false); }}><span className={styles.caseNumber}>0{i + 1}</span><span>{c.title}</span><span aria-hidden="true">↗</span></button>)}<p className={styles.muted}>Three invented collaborations.<br />No organizations or real campaigns represented.</p><a className={styles.textLink} href={`/lab/bottlenecks/?case=${selected}`}>Explore the real case workbench ↗</a></nav><div className={styles.caseBody}><section className={styles.caseBrief}><span className={styles.eyebrow}>SHARED BOTTLENECK <DemoChip /></span><h2>{current.question}</h2><ol className={styles.process}><li>Refine</li><li>Invent a test</li><li>Contribute</li><li>Inspect evidence</li><li>Revise ↺</li></ol><p>{current.outcome}</p></section><DemoCommunityPanel caseId={selected} /><DemoPeople caseId={selected} /></div></div><footer className={styles.footnote}><h2>Useful evidence is the next step. Not a bigger number.</h2><p>Apps and agents can help produce an artifact. Atlas can organize a sourced observation. Points can express interest. None replaces a reviewable contribution or turns an uncertain result into a proven outcome.</p><div className={styles.actions}><a className={styles.textLink} href="/lab/apps/">Explore tools ↗</a><a className={styles.textLink} href="/lab/atlas/">Explore Atlas ↗</a><a className={styles.textLink} href="/lab/collaborate/">Prepare an agent work packet ↗</a></div></footer></> : <section className={styles.empty}><h2>{demo.ready ? 'The stage is clear.' : 'Checking your view preference…'}</h2><p>Fictional profiles, counts, discussions, and notifications are hidden. Your real profile and drafts have not been changed.</p><a className={styles.textLink} href="/lab/profile/">Return to your bench ↗</a></section>}</div>;
}
